#======================================================
# PHYSICS 
#======================================================

/gate/physics/addPhysicsList emstandard_opt4
# possible values for the line after:
# DNA_Opt0, DNA_Opt2, DNA_Opt4, DNA_Opt4a, DNA_Opt6, DNA_Opt6a, DNA_Opt7
/process/em/AddDNARegion Target1 DNA_Opt4
/process/em/AddDNARegion Target3 DNA_Opt4

/gate/physics/Gamma/SetCutInRegion    world 4 um
/gate/physics/Electron/SetCutInRegion   world 4 um
/gate/physics/Positron/SetCutInRegion   world 4 um
/gate/physics/Proton/SetCutInRegion     world 4 um

#======================================================
# ACTORS   
#======================================================

# To avoid very low energy electrons to be trapped into scattering
/gate/actor/addActor  KillActor  killETarget1
/gate/actor/killETarget1/attachTo Target1
/gate/actor/killETarget1/addFilter energyFilter
/gate/actor/killETarget1/energyFilter/setEmax 8 eV

/gate/actor/addActor  KillActor  killETarget3
/gate/actor/killETarget3/attachTo Target3
/gate/actor/killETarget3/addFilter energyFilter
/gate/actor/killETarget3/energyFilter/setEmax 8 eV

