#############
# DIGITIZER #
#############
/gate/digitizerMgr/pixel/SinglesDigitizer/Singles/insert adder
/gate/digitizerMgr/pixel/SinglesDigitizer/Singles/insert readout
/gate/digitizerMgr/pixel/SinglesDigitizer/Singles/readout/setDepth 2
/gate/digitizerMgr/pixel/SinglesDigitizer/Singles/insert energyFraming
/gate/digitizerMgr/pixel/SinglesDigitizer/Singles/energyFraming/setMin 10 keV

/gate/digitizerMgr/verbose 0
