
# -----------------------------------------------------------------------------
# Alias

# Need alias RADIONUCLIDE  => In111 or Tc99m or Lu177 or I131
# Need alias N             => ion activity in Bq 
# Need alias SPECT_RADIUS  => in cm (25 for example)

/control/alias HEAD_NB 1
/control/execute mac/alias.mac

# -----------------------------------------------------------------------------
# Geometry definition

#/control/execute mac/visu.mac
/control/execute mac/verbose.mac
/control/execute mac/world.mac
/control/execute mac/phantom_ct.mac
/control/execute mac/spect_fake_head.mac
/control/execute mac/nm670/spect_translation.mac
/control/execute mac/spect_detector_input_plane_{COLLIMATOR}.mac

# -----------------------------------------------------------------------------
# Physics

/control/execute mac/physics_list.mac
/control/execute mac/physics_cuts_world.mac
/control/execute mac/physics_cuts_phantom.mac

# -----------------------------------------------------------------------------
# OUTPUT

/control/execute mac/output_stat.mac
/gate/verbose Actor      2

/control/strdoif {RADIONUCLIDE} == {TECHNETIUM} /control/alias PT_FILE data/pth/arf_Tc99m_v2
/control/strdoif {RADIONUCLIDE} == {INDIUM} /control/alias     PT_FILE data/pth/arf_In111_v2
/control/strdoif {RADIONUCLIDE} == {LUTETIUM} /control/alias   PT_FILE data/pth/arf_Lu177_v2
/control/strdoif {RADIONUCLIDE} == {IODINE} /control/alias     PT_FILE data/pth/arf_I131_v2

/control/listAlias

/gate/actor/addActor                   NN_ARF_Actor arf
/gate/actor/arf/setMode                predict
/gate/actor/arf/attachTo               detPlane
/gate/actor/arf/setNNModel             {PT_FILE}.pt
/gate/actor/arf/setNNDict              {PT_FILE}.json
/gate/actor/arf/save                   output/projection.mhd
/gate/actor/arf/setSpacingX            4.41806
/gate/actor/arf/setSpacingY            4.41806
/gate/actor/arf/setSizeX               128
/gate/actor/arf/setSizeY               128
/gate/actor/arf/setCollimatorLength    99                   # FIXME explicit mm (unit)
/gate/actor/arf/setBatchSize           1e5
/gate/actor/arf/setEnergyWindowNames   {WINDOWS}


# -----------------------------------------------------------------------------
# INITIALISATION

/gate/run/initialize

# -----------------------------------------------------------------------------
# SOURCE

/control/execute mac/source_vox.mac


# -----------------------------------------------------------------------------
# START

/control/execute mac/start_time.mac



