
## ---------------------------
## This is the source of gamma
## ---------------------------

/gate/source/addSource RadionuclideSource voxel
/gate/source/RadionuclideSource/reader/insert image
/gate/source/RadionuclideSource/imageReader/translator/insert linear

/control/multiply ACTIVITY_SCALE {ACTIVITY_SCALE} 0.94659
/gate/source/RadionuclideSource/imageReader/linearTranslator/setScale {ACTIVITY_SCALE} Bq

# because rotation is controled by attached patient --> DO NOT USE THIS COMMAND
#/gate/source/RadionuclideSource/setRotationAroundPixelIsoCenter 

/gate/source/RadionuclideSource/imageReader/readFile {SOURCE}
/gate/source/RadionuclideSource/TranslateTheSourceAtThisIsoCenter {SOURCE_ISOCENTER_X} {SOURCE_ISOCENTER_Y} {SOURCE_ISOCENTER_Z} mm

/gate/source/RadionuclideSource/gps/angtype iso
/gate/source/RadionuclideSource/gps/particle gamma
/gate/source/RadionuclideSource/gps/angtype iso
/gate/source/RadionuclideSource/gps/energytype UserSpectrum
/gate/source/RadionuclideSource/gps/setSpectrumFile data/energy_spectrum_I131.txt

/gate/source/RadionuclideSource/setForcedHalfLife 693211 s
