
# GE Discovery 670
# Digitizer for Iodine-131
#
# 364.5keV, 637keV and 723keV for the main photopeaks

# Adder
/gate/digitizer/Singles/insert adder

# Readout
/gate/digitizer/Singles/insert readout
#/gate/digitizer/Singles/readout/setPolicy TakeEnergyCentroid
/gate/digitizer/Singles/readout/setDepth 1


# Intrinsic Spatial Blurring
/gate/digitizer/Singles/insert spblurring
/gate/digitizer/Singles/spblurring/setSpresolution 3.97 mm
/gate/digitizer/Singles/spblurring/verbose 0

# Energy Blurring
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setLaw linear
/gate/digitizer/Singles/blurring/linear/setResolution 0.15
/gate/digitizer/Singles/blurring/linear/setEnergyOfReference 364.0 keV
/gate/digitizer/Singles/blurring/linear/setSlope -0.0194 1/MeV

# Thresholds I131
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 3. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 770. keV

# Scatter  1
/gate/digitizer/name scatter1
/gate/digitizer/insert singleChain
/gate/digitizer/scatter1/setInputName Singles
/gate/digitizer/scatter1/insert thresholder
/gate/digitizer/scatter1/thresholder/setThreshold 314 keV
/gate/digitizer/scatter1/insert upholder
/gate/digitizer/scatter1/upholder/setUphold 336 keV

# Peak 1 364.5 keV
/gate/digitizer/name peak364
/gate/digitizer/insert singleChain
/gate/digitizer/peak364/setInputName Singles
/gate/digitizer/peak364/insert thresholder
/gate/digitizer/peak364/thresholder/setThreshold 336 keV
/gate/digitizer/peak364/insert upholder
/gate/digitizer/peak364/upholder/setUphold 392 keV

# Scatter 2
/gate/digitizer/name scatter2
/gate/digitizer/insert singleChain
/gate/digitizer/scatter2/setInputName Singles
/gate/digitizer/scatter2/insert thresholder
/gate/digitizer/scatter2/thresholder/setThreshold 392 keV
/gate/digitizer/scatter2/insert upholder
/gate/digitizer/scatter2/upholder/setUphold 414 keV

# Scatter 3
/gate/digitizer/name scatter3
/gate/digitizer/insert singleChain
/gate/digitizer/scatter3/setInputName Singles
/gate/digitizer/scatter3/insert thresholder
/gate/digitizer/scatter3/thresholder/setThreshold 414 keV
/gate/digitizer/scatter3/insert upholder
/gate/digitizer/scatter3/upholder/setUphold 556 keV

# Scatter 4
/gate/digitizer/name scatter4
/gate/digitizer/insert singleChain
/gate/digitizer/scatter4/setInputName Singles
/gate/digitizer/scatter4/insert thresholder
/gate/digitizer/scatter4/thresholder/setThreshold 556 keV
/gate/digitizer/scatter4/insert upholder
/gate/digitizer/scatter4/upholder/setUphold 595 keV

# Peak 2 637 keV
/gate/digitizer/name peak637
/gate/digitizer/insert singleChain
/gate/digitizer/peak637/setInputName Singles
/gate/digitizer/peak637/insert thresholder
/gate/digitizer/peak637/thresholder/setThreshold 595 keV
/gate/digitizer/peak637/insert upholder
/gate/digitizer/peak637/upholder/setUphold 679 keV

# Peak 3 722 keV
/gate/digitizer/name peak722
/gate/digitizer/insert singleChain
/gate/digitizer/peak722/setInputName Singles
/gate/digitizer/peak722/insert thresholder
/gate/digitizer/peak722/thresholder/setThreshold 679 keV
/gate/digitizer/peak722/insert upholder
/gate/digitizer/peak722/upholder/setUphold 765 keV

