
# -----------------------------------------------------------------------------
# SPECT

# Need at least 28 Radius to avoid collision at 90 degrees

/control/execute mac/nm670/spect_head.mac
/control/execute mac/nm670/spect_collimator_{COLLIMATOR}.mac
/control/execute mac/nm670/spect_digitizer_{RADIONUCLIDE}.mac
/control/execute mac/nm670/spect_translation.mac
/control/execute mac/nm670/spect_rotation.mac

# Repeat : two heads
/gate/SPECThead/repeaters/insert ring
/gate/SPECThead/ring/combineWithRotationFirst true
/gate/SPECThead/ring/setRepeatNumber {HEAD_NB}
/gate/SPECThead/ring/setPoint1 0 0 0
/gate/SPECThead/ring/setPoint2 0 0 1


