
# ---------------------------------------------
# Verbose
#/control/execute mac/verbose.mac

# ---------------------------------------------
# Material Database
/gate/geometry/setMaterialDatabase data/GateMaterials.db

# ---------------------------------------------
# World
/gate/world/geometry/setXLength 2 m
/gate/world/geometry/setYLength 2 m
/gate/world/geometry/setZLength 2 m
/gate/world/vis/setColor white
/gate/world/vis/forceWireframe
/gate/world/setMaterial Air

