
# Output: projection images
/gate/output/projection/enable
/gate/output/projection/setFileName output/projection

/gate/output/projection/addInputDataName scatter1
/gate/output/projection/addInputDataName peak364
/gate/output/projection/addInputDataName scatter2
/gate/output/projection/addInputDataName scatter3
/gate/output/projection/addInputDataName scatter4
/gate/output/projection/addInputDataName peak637
/gate/output/projection/addInputDataName peak722

/gate/output/projection/pixelSizeX 4.41806 mm
/gate/output/projection/pixelSizeY 4.41806 mm
/gate/output/projection/pixelNumberX 128
/gate/output/projection/pixelNumberY 128
/gate/output/projection/projectionPlane XY

