
# ============================
# == actor              ==
# ============================

/gate/actor/addActor  ComptonCameraActor                CC_digi_BB
/gate/actor/CC_digi_BB/attachTo                         BB
/gate/actor/CC_digi_BB/save                               output/CC_idealprocessing.root


/gate/actor/CC_digi_BB/saveHitsTree                           0
/gate/actor/CC_digi_BB/saveSinglesTree                        1
/gate/actor/CC_digi_BB/saveCoincidencesTree                   0
/gate/actor/CC_digi_BB/saveCoincidenceChainsTree              1


/gate/actor/CC_digi_BB/absorberSDVolume                      absorber
/gate/actor/CC_digi_BB/scattererSDVolume                    scatterer
/gate/actor/CC_digi_BB/numberOfTotScatterers                    2

/gate/actor/CC_digi_BB/enableEnergyFin 1
/gate/actor/CC_digi_BB/enableEnergyIni 1

/gate/digitizer/layers/insert adderComptPhotIdeal
/gate/digitizer/layers/adderComptPhotIdeal/rejectEvtOtherProcesses 1


/gate/digitizer/Coincidences/setWindow 3. ns 
/gate/digitizer/Coincidences/setPresortBufferSize 32

/gate/digitizer/name sequenceCoincidence  
/gate/digitizer/insert coincidenceChain 
/gate/digitizer/sequenceCoincidence/addInputName Coincidences

/gate/digitizer/sequenceCoincidence/insert sequenceRecon  
/gate/digitizer/sequenceCoincidence/sequenceRecon/setSequencePolicy singlesTime



