



/gate/source/addSource gammaP
/gate/source/gammaP/gps/particle gamma
/gate/source/gammaP/gps/energytype Mono
/gate/source/gammaP/gps/monoenergy 662 keV
/gate/source/gammaP/setActivity 0.847 MBq

#/gate/source/gammaP/gps/type Plane
#/gate/source/gammaP/gps/shape Circle
#/gate/source/gammaP/gps/radius  0.25 mm
/gate/source/gammaP/gps/angtype iso
/gate/source/gammaP/gps/centre 0. 0.0 0.0 mm



/gate/source/list




