

# -----------------------------------------------------
# LINAC
# -----------------------------------------------------

/gate/world/daughters/name           linac
/gate/world/daughters/insert         box
/gate/linac/setMaterial              Air
/gate/linac/geometry/setXLength      0.5 m
/gate/linac/geometry/setYLength      0.5 m
/gate/linac/geometry/setZLength      0.8 m
/gate/linac/placement/setTranslation 0 0 0 mm
/gate/linac/vis/setVisible           1
/gate/linac/vis/setColor             yellow

# -----------------------------------------------------
# TARGET
# -----------------------------------------------------

/control/execute mac/linac_target.mac

# -----------------------------------------------------
# PRIMARY_COLLIMATOR
# -----------------------------------------------------

/control/execute mac/linac_primary_collimator.mac


# -----------------------------------------------------
# FLATTENING_FILTER
# -----------------------------------------------------

/control/execute mac/linac_flattening_filter.mac

# -----------------------------------------------------
# IONIZING_CHAMBER
# -----------------------------------------------------

/control/execute mac/linac_ionizing_chamber.mac


# -----------------------------------------------------
# BACK_SCATTER_PLATE
# -----------------------------------------------------

/control/execute mac/linac_back_scatter_plate.mac

# -----------------------------------------------------
# MIRROR
# -----------------------------------------------------

/control/execute mac/linac_mirror.mac

# -----------------------------------------------------
# KILLING BOX: to kill particle in some regions (when they dont go in
# the good direction) and thus gain time
# -----------------------------------------------------

/gate/linac/daughters/name                      kill_box_top
/gate/linac/daughters/insert                    cylinder
/gate/kill_box_top/setMaterial                  Vacuum
/gate/kill_box_top/geometry/setRmin             0 mm
/gate/kill_box_top/geometry/setRmax             30 mm
/gate/kill_box_top/geometry/setHeight           20 mm
/gate/kill_box_top/placement/setTranslation     0.0 0.0 21 mm
/gate/kill_box_top/vis/setVisible               0

/gate/linac/daughters/name                      kill_box_bottom
/gate/linac/daughters/insert                    cylinder
/gate/kill_box_bottom/setMaterial               Vacuum
/gate/kill_box_bottom/geometry/setRmin          16 mm
/gate/kill_box_bottom/geometry/setRmax          30 mm
/gate/kill_box_bottom/geometry/setHeight        21.5 mm
/gate/kill_box_bottom/placement/setTranslation  0.0 0.0 0.25 mm
/gate/kill_box_bottom/vis/setVisible            0

/gate/linac/daughters/name                      kill_box_bottom2
/gate/linac/daughters/insert                    cylinder
/gate/kill_box_bottom2/setMaterial              Vacuum
/gate/kill_box_bottom2/geometry/setRmin         30 mm
/gate/kill_box_bottom2/geometry/setRmax         50 cm
/gate/kill_box_bottom2/geometry/setHeight       21.5 mm
/gate/kill_box_bottom2/placement/setTranslation 0.0 0.0 0.25 mm
/gate/kill_box_bottom2/vis/setVisible           0
