# -----------------------------------------------------
# TARGET
# -----------------------------------------------------

/gate/linac/daughters/name                    target_support
/gate/linac/daughters/insert                  cylinder
/gate/target_support/setMaterial              Air
/gate/target_support/geometry/setRmin         0 mm  
/gate/target_support/geometry/setRmax         15 mm
/gate/target_support/geometry/setHeight       11 mm
/gate/target_support/placement/setTranslation 0.0 0.0 -5 mm
/gate/target_support/vis/setVisible 0

	/gate/target_support/daughters/name   target
	/gate/target_support/daughters/insert cylinder
	/gate/target/setMaterial              AcceleratorTargetMaterial
	/gate/target/geometry/setRmin         0 mm  
	/gate/target/geometry/setRmax         2.70 mm
	/gate/target/geometry/setHeight       1.00 mm
        /gate/target/placement/setTranslation 0 0 +5 mm
        /gate/target/vis/setColor             red
        /gate/target/vis/setVisible           1

	/gate/target_support/daughters/name               target_support_top
	/gate/target_support/daughters/insert             cylinder
	/gate/target_support_top/setMaterial              Copper
	/gate/target_support_top/geometry/setRmin         2.70 mm  
	/gate/target_support_top/geometry/setRmax         15 mm
	/gate/target_support_top/geometry/setHeight       1.00 mm
	/gate/target_support_top/placement/setTranslation 0.0 0.0 +5.0 mm
        /gate/target_support_top/vis/setColor             green
        /gate/target_support_top/vis/setVisible           1
	
	/gate/target_support/daughters/name                  target_support_bottom
	/gate/target_support/daughters/insert                cylinder
	/gate/target_support_bottom/setMaterial              Copper
	/gate/target_support_bottom/geometry/setRmin         0 mm  
	/gate/target_support_bottom/geometry/setRmax         15 mm
	/gate/target_support_bottom/geometry/setHeight       10 mm
	/gate/target_support_bottom/placement/setTranslation 0.0 0.0 -0.5 mm
        /gate/target_support_bottom/vis/setColor             green
        /gate/target_support_bottom/vis/setVisible           1
