/gate/world/daughters/name GlobalVol
/gate/world/daughters/insert box
/gate/GlobalVol/geometry/setXLength 301.0 mm
/gate/GlobalVol/geometry/setYLength 301.0 mm
/gate/GlobalVol/geometry/setZLength 301.0 mm
/gate/GlobalVol/placement/setTranslation 0.0 0.0 0.0 mm
/gate/GlobalVol/placement/setRotationAxis 1 0 0
/gate/GlobalVol/placement/setRotationAngle 0 deg
/gate/GlobalVol/setMaterial Vacuum
/gate/GlobalVol/vis/setColor cyan
/gate/GlobalVol/describe
