
# Physics
/gate/physics/addPhysicsList emstandard_opt1
/gate/physics/Gamma/SetCutInRegion      SPECThead 1 mm
/gate/physics/Electron/SetCutInRegion   SPECThead 1 mm
/gate/physics/Positron/SetCutInRegion   SPECThead 1 mm

# World
/gate/geometry/setMaterialDatabase data/GateMaterials.db
/gate/world/geometry/setXLength 2 m
/gate/world/geometry/setYLength 2 m
/gate/world/geometry/setZLength 2 m
/gate/world/vis/setColor white
/gate/world/vis/forceWireframe
/gate/physics/Gamma/SetCutInRegion      world 10 mm
/gate/physics/Electron/SetCutInRegion   world 10 m
/gate/physics/Positron/SetCutInRegion   world 10 m

# SPECThead
/gate/world/daughters/name SPECThead
/gate/world/daughters/insert box
/gate/SPECThead/geometry/setXLength 15.3175 cm
/gate/SPECThead/geometry/setYLength 44.6 cm
/gate/SPECThead/geometry/setZLength 57.6 cm
/gate/SPECThead/placement/setTranslation  31.65875 -0. -0. cm
/gate/SPECThead/setMaterial Air

