#--------------------------------------------------------------------------	#
#                                Define primary events				#
#--------------------------------------------------------------------------	#

/control/multiply 			_halfBeamWidth {BeamWidthInCM} 0.5

###################################################################
# Create the beam 1
###################################################################
/gate/source/addSource beam_1 gps
/gate/source/beam_1/gps/particle gamma
/gate/source/beam_1/gps/energytype UserSpectrum
/gate/source/beam_1/gps/setSpectrumFile ./Data/Spectrum1.txt
/gate/source/beam_1/setIntensity 1

# Define the geometry of the source
/gate/source/beam_1/gps/pos/type Plane		
/gate/source/beam_1/gps/pos/shape Rectangle				
/gate/source/beam_1/gps/pos/rot1 0 0 1		# Defines the orientation of the source 
/gate/source/beam_1/gps/pos/rot2 0 1 0		# Defines the orientation of the source.
/gate/source/beam_1/gps/pos/halfx {_halfBeamWidth} cm	# Half the x size of the rectangle
/gate/source/beam_1/gps/pos/halfy {_halfBeamWidth} cm	# Half the y size of the rectangle

# Place the source.
/gate/source/beam_1/gps/pos/centre -0.10 0. 0. m

# The angular distribution of the source
/gate/source/beam_1/gps/direction 1 0 0		

# Visualize placement of source
/gate/source/beam_1/visualize 100 red 2
###################################################################


###################################################################
# Create the beam 2
###################################################################
/gate/source/addSource beam_2 gps
/gate/source/beam_2/gps/particle gamma
/gate/source/beam_2/gps/energytype UserSpectrum
/gate/source/beam_2/gps/setSpectrumFile ./Data/Spectrum2.txt
/gate/source/beam_2/setIntensity 1

# Define the geometry of the source
/gate/source/beam_2/gps/pos/type Plane		
/gate/source/beam_2/gps/pos/shape Rectangle				
/gate/source/beam_2/gps/pos/rot1 0 0 1		# Defines the orientation of the source 
/gate/source/beam_2/gps/pos/rot2 1 0 0		# Defines the orientation of the source.
/gate/source/beam_2/gps/pos/halfx {_halfBeamWidth} cm	# Half the x size of the rectangle
/gate/source/beam_2/gps/pos/halfy {_halfBeamWidth} cm	# Half the y size of the rectangle

# Place the source.
/gate/source/beam_2/gps/pos/centre 0. -0.10 0. m

# The angular distribution of the source
/gate/source/beam_2/gps/direction 0 1 0		

# Visualize placement of source
/gate/source/beam_2/visualize 100 red 2
###################################################################


/control/unalias _halfBeamWidth

