#	D I G I T I Z E R
/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/insert adder
/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/insert adder

/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/insert                        merger
/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/merger/addInput  adder/Singles_LSO

/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/insert readout
/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/readout/setDepth 1
/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/insert energyResolution
/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/energyResolution/fwhm 0.26
/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/energyResolution/energyOfReference 511. keV
/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/insert energyFraming
/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/energyFraming/setMin 350. keV
/gate/digitizerMgr/BGO/SinglesDigitizer/Singles/energyFraming/setMax 650. keV



#	C O I N C I    S O R T E R
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setInputCollection Singles_BGO
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setWindow 120. ns
/gate/digitizerMgr/CoincidenceSorter/Coincidences/MultiplesPolicy  takeWinnerOfGoods

/gate/digitizerMgr/name delay
/gate/digitizerMgr/insert CoincidenceSorter
/gate/digitizerMgr/CoincidenceSorter/delay/setInputCollection Singles_BGO
/gate/digitizerMgr/CoincidenceSorter/delay/setWindow 120. ns
/gate/digitizerMgr/CoincidenceSorter/delay/setOffset 500. ns
/gate/digitizerMgr/CoincidenceSorter/delay/MultiplesPolicy  takeWinnerOfGoods


