/gate/source/addSource                          PointSrc gps
/gate/source/PointSrc/gps/particle              gamma
/gate/source/PointSrc/setForcedUnstableFlag     false
/gate/source/PointSrc/gps/energytype            Mono
/gate/source/PointSrc/gps/monoenergy            100 keV
/gate/source/PointSrc/gps/type                  Point
/gate/source/PointSrc/gps/centre                -55. 0. 0. mm
/gate/source/PointSrc/gps/posrot1               0 0 1
/gate/source/PointSrc/gps/posrot2               0 1 0
/gate/source/PointSrc/gps/angrot1               0 0 1
/gate/source/PointSrc/gps/angrot2               0 1 0
/gate/source/PointSrc/gps/ang/mintheta          0.0 deg
/gate/source/PointSrc/gps/ang/maxtheta          0.0 deg
/gate/source/PointSrc/gps/ang/minphi            0.0 deg
/gate/source/PointSrc/gps/ang/maxphi            360.0 deg
/gate/source/PointSrc/gps/angtype               iso
/gate/source/PointSrc/dump                      1
